[project]
name = "grpo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.7",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "torch>=2.8.0",
    "vllm>=0.11.0",
]
